/* tslint:disable */
/* eslint-disable */
/**
 * Chamel
 * The Chamel API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateMessageDTO
 */
export interface CreateMessageDTO {
    /**
     * Message text
     * @type {string}
     * @memberof CreateMessageDTO
     */
    text: string;
    /**
     * Receiver id
     * @type {string}
     * @memberof CreateMessageDTO
     */
    receiverId: string;
    /**
     * Sender id
     * @type {string}
     * @memberof CreateMessageDTO
     */
    senderId: string;
}

/**
 * Check if a given object implements the CreateMessageDTO interface.
 */
export function instanceOfCreateMessageDTO(value: object): value is CreateMessageDTO {
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('receiverId' in value) || value['receiverId'] === undefined) return false;
    if (!('senderId' in value) || value['senderId'] === undefined) return false;
    return true;
}

export function CreateMessageDTOFromJSON(json: any): CreateMessageDTO {
    return CreateMessageDTOFromJSONTyped(json, false);
}

export function CreateMessageDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMessageDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
        'receiverId': json['receiverId'],
        'senderId': json['senderId'],
    };
}

export function CreateMessageDTOToJSON(json: any): CreateMessageDTO {
    return CreateMessageDTOToJSONTyped(json, false);
}

export function CreateMessageDTOToJSONTyped(value?: CreateMessageDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'receiverId': value['receiverId'],
        'senderId': value['senderId'],
    };
}

