/* tslint:disable */
/* eslint-disable */
/**
 * Chamel
 * The Chamel API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CMessage
 */
export interface CMessage {
  /**
   * Message id
   * @type {string}
   * @memberof CMessage
   */
  id: string
  /**
   * Message text
   * @type {string}
   * @memberof CMessage
   */
  text: string
  /**
   * Sender id
   * @type {string}
   * @memberof CMessage
   */
  senderId: string
  /**
   * Receiver id
   * @type {string}
   * @memberof CMessage
   */
  receiverId: string
}

/**
 * Check if a given object implements the CMessage interface.
 */
export function instanceOfMessageC(value: object): value is CMessage {
  if (!('id' in value) || value['id'] === undefined) return false
  if (!('text' in value) || value['text'] === undefined) return false
  if (!('senderId' in value) || value['senderId'] === undefined) return false
  if (!('receiverId' in value) || value['receiverId'] === undefined) return false
  return true
}

export function MessageCFromJSON(json: any): CMessage {
  return MessageCFromJSONTyped(json, false)
}

export function MessageCFromJSONTyped(json: any, ignoreDiscriminator: boolean): CMessage {
  if (json == null) {
    return json
  }
  return {
    id: json['id'],
    text: json['text'],
    senderId: json['senderId'],
    receiverId: json['receiverId'],
  }
}

export function MessageCToJSON(json: any): CMessage {
  return MessageCToJSONTyped(json, false)
}

export function MessageCToJSONTyped(
  value?: CMessage | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    id: value['id'],
    text: value['text'],
    senderId: value['senderId'],
    receiverId: value['receiverId'],
  }
}
