/* tslint:disable */
/* eslint-disable */
/**
 * Chamel
 * The Chamel API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignUpDTO
 */
export interface SignUpDTO {
    /**
     * User name
     * @type {string}
     * @memberof SignUpDTO
     */
    name: string;
    /**
     * User email
     * @type {string}
     * @memberof SignUpDTO
     */
    email: string;
    /**
     * User password
     * @type {string}
     * @memberof SignUpDTO
     */
    password: string;
}

/**
 * Check if a given object implements the SignUpDTO interface.
 */
export function instanceOfSignUpDTO(value: object): value is SignUpDTO {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function SignUpDTOFromJSON(json: any): SignUpDTO {
    return SignUpDTOFromJSONTyped(json, false);
}

export function SignUpDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignUpDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'email': json['email'],
        'password': json['password'],
    };
}

export function SignUpDTOToJSON(json: any): SignUpDTO {
    return SignUpDTOToJSONTyped(json, false);
}

export function SignUpDTOToJSONTyped(value?: SignUpDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'email': value['email'],
        'password': value['password'],
    };
}

