/* tslint:disable */
/* eslint-disable */
/**
 * Chamel
 * The Chamel API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignInDTO
 */
export interface SignInDTO {
    /**
     * User email
     * @type {string}
     * @memberof SignInDTO
     */
    email: string;
    /**
     * User password
     * @type {string}
     * @memberof SignInDTO
     */
    password: string;
}

/**
 * Check if a given object implements the SignInDTO interface.
 */
export function instanceOfSignInDTO(value: object): value is SignInDTO {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function SignInDTOFromJSON(json: any): SignInDTO {
    return SignInDTOFromJSONTyped(json, false);
}

export function SignInDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignInDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function SignInDTOToJSON(json: any): SignInDTO {
    return SignInDTOToJSONTyped(json, false);
}

export function SignInDTOToJSONTyped(value?: SignInDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

