/* tslint:disable */
/* eslint-disable */
/**
 * Chamel
 * The Chamel API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenC
 */
export interface TokenC {
    /**
     * accessToken
     * @type {string}
     * @memberof TokenC
     */
    accessToken: string;
    /**
     * refreshToken
     * @type {string}
     * @memberof TokenC
     */
    refreshToken: string;
}

/**
 * Check if a given object implements the TokenC interface.
 */
export function instanceOfTokenC(value: object): value is TokenC {
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
    return true;
}

export function TokenCFromJSON(json: any): TokenC {
    return TokenCFromJSONTyped(json, false);
}

export function TokenCFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenC {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['accessToken'],
        'refreshToken': json['refreshToken'],
    };
}

export function TokenCToJSON(json: any): TokenC {
    return TokenCToJSONTyped(json, false);
}

export function TokenCToJSONTyped(value?: TokenC | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
    };
}

