/* tslint:disable */
/* eslint-disable */
/**
 * Chamel
 * The Chamel API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserC
 */
export interface UserC {
    /**
     * User id
     * @type {string}
     * @memberof UserC
     */
    id: string;
    /**
     * User name
     * @type {string}
     * @memberof UserC
     */
    name: string;
    /**
     * User email
     * @type {string}
     * @memberof UserC
     */
    email: string;
}

/**
 * Check if a given object implements the UserC interface.
 */
export function instanceOfUserC(value: object): value is UserC {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function UserCFromJSON(json: any): UserC {
    return UserCFromJSONTyped(json, false);
}

export function UserCFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserC {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'email': json['email'],
    };
}

export function UserCToJSON(json: any): UserC {
    return UserCToJSONTyped(json, false);
}

export function UserCToJSONTyped(value?: UserC | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'email': value['email'],
    };
}

